title: "Jagath Kumar Reddy"
description: "Focused on training robust models and optimizing inference for efficient AI solutions."
logo: "/photo.jpeg"
theme: jekyll-theme-minimal
author: "Jagath Kumar Reddy"
