title: "Jagath Kumar Reddy"
description: " Actively involved in Neural nets Models and Optimizations of them"
logo: "/portfolio/Formal_photo(1).jpeg"
theme: jekyll-theme-minimal
author: "Jagath Kumar Reddy"
